apiVersion: harness.io/v1
kind: Component
type: service
identifier: testscorecard23
name: testscorecard23
owner: user:account/manisha.choudhary@harness.io
orgIdentifier: default
projectIdentifier: Manisha
spec:
  lifecycle: production
metadata:
  tags:
  - java
  - dev
  - qa
