apiVersion: harness.io/v1
kind: Component
type: service
identifier: testscorecard23
name: testscorecard23
owner: user:account/manisha.choudhary@harness.io
orgIdentifier: default
projectIdentifier: Manisha
spec:
  lifecycle: production
  sourceCode:
    provider: Github
    repoName: Demo
    connectorRef: account.Freshgithubconnector
    branch: main
    monoRepo: false
    url: https://github.com/mehar221/Demo/tree/main
metadata:
  tags:
  - java
  - dev
  - qa
